# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Costa Rica Freeriders
email: bryanba8@hotmail.com
description:  Freeriding around the World! And then every moment becomes Incredible, Unglaublich, Incroyable
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.costaricafreeriders.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
